name: Code Quality

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    merge_group:
        types:
            - checks_requested

permissions:
    contents: read

jobs:
    check-permissions:
        runs-on: ubuntu-latest
        outputs:
            is-authorized: ${{ steps.check-permissions.outputs.is-authorized }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Check Permissions
              id: check-permissions
              uses: ./.github/actions/check-permissions

    lint:
        needs: check-permissions
        if: needs.check-permissions.outputs.is-authorized == 'true'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup
              uses: Act-Aks/cached-setup@v1.1.1

            - name: Lint files
              run: yarn lint

            - name: Typecheck files
              run: yarn typecheck

    test:
        needs: check-permissions
        if: needs.check-permissions.outputs.is-authorized == 'true'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup
              uses: Act-Aks/cached-setup@v1.1.1

            - name: Run unit tests
              run: yarn test --maxWorkers=2 --coverage
